### ISSUE TITLE
Build Automation System Like Gradle/Maven

### ISSUE THREAD

**Issue by sakky11** [nasa/DERT#2]
Hello,
It seems that in NASA/DERT,build is not automated using any tool like Maven/Gradle.Do we have any plan for the same??If yes,I can help you with those.
 I would also like to help you with 100% Unit Test Coverages/System tests/Automation Build Systems along with the main codebase.Please let me know how I can help you in this project.

**Comment by lekeely** [comment]
Sakky11, these are good ideas.  However, we are not able to add new contributors at this time. You can help us by testing DERT and reporting any issues you find. Thank you for your generous offer.
