### ISSUE TITLE
release links connection timeout

### ISSUE THREAD

**Issue by AndrewAnnex** [nasa/DERT#4]
It looks like the release links are broken again, although they were working a month or two ago. Would it be possible to upload them to the github release, or is there a filesize limit there?

**Comment by lekeely** [comment]
I contacted our sysadmin.  Yes there is a file size limit due to the spice kernels. You can also get the releases in the Github release tab.  Run the script "get_kernels" in the installation directory to download the spice kernels.

**Comment by lekeely** [comment]
This should be fixed now.
