### ISSUE TITLE
allow faster flythrough framerate when saving animation image sequence

### ISSUE THREAD

**Issue by AndrewAnnex** [nasa/DERT#7]
I have had great success recently using DERT to produce smooth animations. I have been producing short 60fps videos by having DERT render 1000 frames to disk and then using ffmpeg, however there is a hard set limit in Animator.java that sets the rate at 1 frame per second when rendering the image sequence. It would be great if this were configurable for cases when rendering to disk, even reducing this to 100ms or 50ms per frame would be a massive improvement. 
I have also had decent results running the animation in "realtime" without saving to disk and using a screen capture program to capture the animation, but this is a bit more work than just using ffmpeg on the image sequence.

**Comment by lekeely** [comment]
I removed the 1 second constraint in the latest release (1.0.3).
